### ISSUE TITLE
Schedules not being added

### ISSUE THREAD

**Issue by Phelzier** [tdack/unifi-parental#3]
First of all, great work.  It will be useful to plug a big hole missing from the USG.

I got it all up and running yesterday after a little trial and error as I am not an expert on Linux.  I'm running it on the same Raspberry Pi 3 as my UniFi server.  I was able to log into the portal on port 4000, it retrieved the MAC/Hostnames from UniFi.  I set up the schedules using the GUI, which I can see have been saved in the config.json file.

The issue for me is that it did not appear to put any rules in the UniFi server when the device should be blocked.  I was expecting to see a rule in the firewall for WAN out, I checked all the zones just in case, but nothing in there and the kids still had their WiFi.

Any pointers you can give for me to investigate further?

Thanks,
Phelz

**Comment by tdack** [comment]
It doesn't make any changes to the UniFi server.

The scheduling is done by the NodeJS application as a separate function. The clients are simply blocked/unblocked by the NodeJS application using the UniFi API to tell the UniFi server to block/unblock a specific client.

Its not the best method and does require the NodeJS application to be running all the time otherwise the schedules won't trigger.
